AWSTemplateFormatVersion: 2010-09-09
Description: DynamoDB used to store CloudFormation stack emissions
Metadata:
  Source: https://github.com/mozilla/cloudformation-cross-account-outputs
Mappings:
  Variables:
    DynamoDBTable:
      Name: cloudformation-stack-emissions
      AccountIdKey: aws-account-id
      StackIdKey: stack-id
Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: !FindInMap [ Variables, DynamoDBTable, AccountIdKey ]
          AttributeType: S
        - AttributeName: !FindInMap [ Variables, DynamoDBTable, StackIdKey ]
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - KeyType: HASH
          AttributeName: !FindInMap [ Variables, DynamoDBTable, AccountIdKey ]
        - KeyType: RANGE
          AttributeName: !FindInMap [ Variables, DynamoDBTable, StackIdKey ]
      TableName: !FindInMap [ Variables, DynamoDBTable, Name ]
