AWSTemplateFormatVersion: 2010-09-09
Description: DynamoDB used to store CloudFormation stack emissions
Metadata:
  Source: https://github.com/mozilla/cloudformation-cross-account-outputs
  TemplateVersion: 3.0.0
Mappings:
  Variables:
    DynamoDBTable:
      Name: cloudformation-stack-emissions
      LogicalResourceIdKey: logical-resource-id
      StackIdKey: stack-id
Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: !FindInMap [ Variables, DynamoDBTable, StackIdKey ]
          AttributeType: S
        - AttributeName: !FindInMap [ Variables, DynamoDBTable, LogicalResourceIdKey ]
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - KeyType: HASH
          AttributeName: !FindInMap [ Variables, DynamoDBTable, StackIdKey ]
        - KeyType: RANGE
          AttributeName: !FindInMap [ Variables, DynamoDBTable, LogicalResourceIdKey ]
      TableName: !FindInMap [ Variables, DynamoDBTable, Name ]
